# Generated by Django 4.2.1 on 2023-08-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_detail', models.CharField(default='', max_length=1000)),
                ('class_price', models.FloatField(default=0)),
                ('max_gen_per_date', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('col_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetailImgGen',
            fields=[
                ('genDetail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_isPublic', models.BooleanField(default=False)),
                ('gen_message', models.TextField(blank=True, default='', max_length=255)),
                ('gen_star', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Packaging Detail',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(default='none@email.com', max_length=255, unique=True)),
                ('hash_pass', models.CharField(default='', max_length=255)),
                ('pic', models.CharField(default='https://images.unsplash.com/photo-1635614017406-7c192d832072?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=387&q=80', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('regAt', models.DateTimeField(null=True)),
                ('lastLogin', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='', max_length=255)),
                ('classUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.class')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('upgrade_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('duedate', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.IntegerField(default=1)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gen.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noti_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_source', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_detail', models.TextField(default='', max_length=800)),
                ('notice_date', models.DateTimeField(null=True)),
                ('acc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImgGen',
            fields=[
                ('gen_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_source', models.CharField(max_length=255)),
                ('gen_CreateAt', models.DateTimeField()),
                ('acc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.user')),
                ('genDetail_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_gen.detailimggen')),
            ],
            options={
                'verbose_name_plural': 'Packaging',
            },
        ),
        migrations.CreateModel(
            name='Illegal',
            fields=[
                ('cop_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_details', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('gen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gen.imggen')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_date', models.DateTimeField(null=True)),
                ('source_id', models.ManyToManyField(related_name='source_id', to='app_gen.user')),
                ('target_id', models.ManyToManyField(related_name='target_id', to='app_gen.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCollection',
            fields=[
                ('col_detail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gen.collection')),
                ('gen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gen.imggen')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creditNum', models.CharField(max_length=255)),
                ('creditName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('CVC', models.CharField(max_length=4)),
                ('DDVV', models.CharField(max_length=5)),
                ('acc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_gen.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('dueTime', models.DateTimeField(null=True)),
                ('removeAt', models.DateTimeField(null=True)),
                ('gen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.imggen')),
            ],
        ),
    ]
