# Generated by Django 4.2.1 on 2023-08-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imggen',
            name='genDetail_id',
        ),
        migrations.AddField(
            model_name='detailimggen',
            name='gen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.imggen'),
        ),
        migrations.AlterField(
            model_name='imggen',
            name='acc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_gen.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_gen.class'),
        ),
    ]
