# Generated by Django 4.2.1 on 2023-09-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0003_alter_imggen_gen_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImgGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_message', models.TextField(blank=True, default='', max_length=255)),
                ('gen_star', models.IntegerField(default=0)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gen.user')),
                ('gen', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.imggen')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
