# Generated by Django 4.2.1 on 2023-09-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0005_rename_gen_star_commentimggen_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimggen',
            name='like',
        ),
        migrations.AddField(
            model_name='commentimggen',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
