# Generated by Django 4.2.1 on 2023-09-03 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0006_remove_commentimggen_like_commentimggen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimggen',
            name='gen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.imggen'),
        ),
    ]
