# Generated by Django 4.2.1 on 2023-09-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0007_alter_commentimggen_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailimggen',
            name='dueTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='detailimggen',
            name='isRemove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailimggen',
            name='removeAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
    ]
