# Generated by Django 4.2.1 on 2023-10-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0013_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='illegal',
            name='report_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='DetailImgGen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gen.detailimggen'),
        ),
    ]
