# Generated by Django 4.2.1 on 2023-10-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0020_rename_pic_source_upload_notification_pic_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notice_test',
        ),
    ]
