# Generated by Django 4.2.1 on 2023-09-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0004_commentimggen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentimggen',
            old_name='gen_star',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='commentimggen',
            old_name='gen_message',
            new_name='message',
        ),
    ]
