# Generated by Django 4.2.1 on 2023-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0009_collection_total_alter_detailimggen_duetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcollection',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
