# Generated by Django 4.2.1 on 2023-09-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0010_detailcollection_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='total',
        ),
        migrations.RemoveField(
            model_name='detailcollection',
            name='total_amount',
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailImgGen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.detailimggen')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.user')),
            ],
        ),
    ]
