# Generated by Django 4.2.1 on 2023-09-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
