# Generated by Django 4.2.1 on 2023-10-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0014_illegal_report_date_alter_star_detailimggen'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='col_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gen.user'),
        ),
    ]
