# Generated by Django 4.2.1 on 2023-10-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0018_notification_pic_source_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='pic_source',
        ),
    ]
