# Generated by Django 4.2.1 on 2023-10-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen', '0019_remove_notification_pic_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='pic_source_upload',
            new_name='pic_source',
        ),
    ]
